name: Publish to PowerShell Gallery

on:
  release:
    types: [published]
  workflow_dispatch:  # Manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish Module
      run: |
        Install-Module -Name PowerShellGet -Force -AllowClobber
        Publish-Module -Path ./ -NuGetApiKey "${{ secrets.PSGALLERY_API_KEY }}"
      shell: pwsh
